services:
  - type: web
    name: faappciesa
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120 --workers 2"
    envVars:
      - key: MAIL_USERNAME
        value: admonbribiesca@gmail.com
      - key: MAIL_PASSWORD
        value: jgwxfbnglswpidne
