services:
  - type: web
    name: facturacion-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_SENDER
        sync: false
